# Generated by Django 5.0.3 on 2024-08-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=7)),
                ('type', models.CharField(max_length=40)),
                ('estate', models.CharField(max_length=7)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('complement', models.CharField(max_length=255)),
                ('rooms', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
